### ISSUE TITLE
Cannot build Haskell Platform 8.2.1 (building hptool fails)

### ISSUE THREAD

**Issue by mainland** [haskell/haskell-platform#287] opened 2017-10-03 13:52 UTC
I'm unable to build Haskell Platform 8.2.1 from source on Linux (Ubuntu 16.04). The `platform.sh` script fails when building `hptool` whether I try to build it with GHC 8.0.2 or 8.2.1. For example, with 8.0.2 I get errors like the following:

```
[18 of 32] Compiling Config           ( src/Config.hs, /home/mainland/software/haskell-platform-8.2.1/hptool/dist-newstyle/build/x86_64-linux/ghc-8.0.2/hptool-0.1/c/hptool/build/hptool/hptool-tmp/Config.o )

src/Config.hs:27:10: error:
    • Couldn't match type ‘RuleResult q’ with ‘[Char]’
        arising from a use of ‘askOracle’
    • In a stmt of a 'do' block: s <- askOracle q
      In the expression:
        do { s <- askOracle q;
             maybe (error $ msg s) return $ readMaybe reads s }
      In an equation for ‘readOracle’:
          readOracle name q
            = do { s <- askOracle q;
                   maybe (error $ msg s) return $ readMaybe reads s }
            where
                msg s = "readOracle failed to parse " ++ name ++ " from " ++ show s
    • Relevant bindings include
        q :: q (bound at src/Config.hs:26:17)
        readOracle :: String -> q -> Action a (bound at src/Config.hs:26:1)
```

Attempting to use 8.2.1 gives similar results.

I'm curious, what is the procedure for building the Linux installers?

I have always built the platform from source (don't ask...), an my procedure for recent platforms is as follows:

 1. Build the GHC bindist.
 1. Build the required versions of `cabal-install` and `stack`, which I get from `haskell-platform.cabal`, with the previous version of GHC.
 1. Pass these three arguments to `platform.sh`.

That doesn't seem to work anymore. What should I be doing differently?

**Comment by gbaz** [comment] 2017-10-03 14:42
My best guess is that there's likely recently been a shake release that has some backwards-incompat changes. The quick fix would be to add some bounds to `hptool`'s cabal.

**Comment by 23Skidoo** [comment] 2017-10-03 14:49
See http://neilmitchell.blogspot.co.uk/2017/09/shake-016-revised-rule-definitions.html. Fixing that error is quite easy.

**Comment by 23Skidoo** [comment] 2017-10-03 15:56
#288 is a duplicate of this issue.

**Comment by randen** [comment] 2017-10-03 16:16
I submitted the new issue to cover the specific work.  And now we can close this issue in deference to that one, #288.

**Closed by randen** 2017-10-03 16:16 UTC
